name: Deploy to Walrus Mainnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: "walrus-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Install Walrus Sites Deploy
      run: npm install -g walrus-sites-deploy
      
    - name: Setup Suibase
      run: |
        curl -fsSL https://raw.githubusercontent.com/suibase/suibase/main/scripts/common/install.sh | bash
        export PATH="$HOME/.local/bin:$PATH"
        ~/suibase/scripts/start mainnet
        
    - name: Configure Sui Wallet
      run: |
        mkdir -p ~/.sui/sui_config
        echo "${{ secrets.SUI_PRIVATE_KEY }}" > ~/.sui/sui_config/sui.keystore
        sui client switch --env mainnet
        sui client switch --address 0x8de8fac3c17c10311b7e0fb8ed8c972e42eac5732388af83ccf8e320ff226ee8
        
    - name: Deploy to Walrus Sites
      if: github.ref == 'refs/heads/main'
      run: |
        cd dist
        pnpx walrus-sites-deploy --network mainnet --epochs 5
      env:
        SUI_PRIVATE_KEY: ${{ secrets.SUI_PRIVATE_KEY }}
        
    - name: Save Site Info
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment completed!"
        if [ -f ".walrus-site-id" ]; then
          echo "Site ID: $(cat .walrus-site-id)"
          echo "Site URL: https://$(cat .walrus-site-id).wal.app"
        fi