name: Deploy to Walrus Mainnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: "walrus-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Install Walrus Sites Deploy
      run: npm install -g walrus-sites-deploy
      
    - name: Install Sui CLI
      run: |
        # Download and install Sui CLI
        SYSTEM="ubuntu-x86_64"
        curl -L "https://github.com/MystenLabs/sui/releases/latest/download/sui-$SYSTEM-ubuntu.tgz" -o sui.tgz
        tar -xzf sui.tgz
        sudo mv sui-$SYSTEM-ubuntu/sui /usr/local/bin/sui
        chmod +x /usr/local/bin/sui
        
    - name: Configure Sui Wallet
      run: |
        # Initialize Sui configuration
        mkdir -p ~/.sui/sui_config
        
        # Create basic client config
        cat > ~/.sui/sui_config/client.yaml << EOF
        keystore:
          File: ~/.sui/sui_config/sui.keystore
        envs:
          - alias: mainnet
            rpc: "https://fullnode.mainnet.sui.io:443"
            ws: ~
            basic_auth: ~
        active_env: mainnet
        active_address: "0x8de8fac3c17c10311b7e0fb8ed8c972e42eac5732388af83ccf8e320ff226ee8"
        EOF
        
        # Import private key
        echo "${{ secrets.SUI_PRIVATE_KEY }}" | sui keytool import ed25519 --alias deployment-key
        
    - name: Deploy to Walrus Sites
      if: github.ref == 'refs/heads/main'
      run: |
        cd dist
        pnpx walrus-sites-deploy --network mainnet --epochs 5
      env:
        SUI_PRIVATE_KEY: ${{ secrets.SUI_PRIVATE_KEY }}
        
    - name: Save Site Info
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment completed!"
        if [ -f ".walrus-site-id" ]; then
          echo "Site ID: $(cat .walrus-site-id)"
          echo "Site URL: https://$(cat .walrus-site-id).wal.app"
        fi